#!/usr/bin/perl -w

# systemd-memcached-wrapper
# 2014 - Christos Trochalakis <yatiohi@idepolis.gr>
#
# Heavily based on start-memcached script by Jay Bonci
# <jaybonci@debian.org>
#
# This script handles the parsing of the /etc/memcached.conf file
# and was originally created for the Debian distribution.
# Anyone may use this little script under the same terms as
# memcached itself.

use strict;

if($> != 0 and $< != 0)
{
    print STDERR "Only root wants to run systemd-memcached-wrapper.\n";
    exit;
}

my $params; my $etchandle; my $etcfile = "/etc/memcached.conf";

# This script assumes that memcached is located at /usr/bin/memcached
my $memcached = "/usr/bin/memcached";

if (scalar(@ARGV) == 1) {
    $etcfile = shift(@ARGV);
}

# systemd capture stdout by default
my $ignore_directives = ("logfile");

if(open $etchandle, $etcfile)
{
    foreach my $line (<$etchandle>)
    {
        $line ||= "";
        $line =~ s/(?<!\\)\#[^\#]*//g;
        $line =~ s/\s+$//g;
        $line =~ s/^\s+//g;
        next unless $line;
        next if $line =~ /^\-[dh]/;

        if($line =~ /^[^\-]/)
        {
            my ($directive, $arg) = $line =~ /^(.*?)\s+(.*)/;
	    next if(grep $directive, $ignore_directives);
        }

        push @$params, $line;
    }

}else{
    $params = [];
}

push @$params, "-u root" unless(grep "-u", @$params);
$params = join " ", @$params;

exec "$memcached $params";
exit(0);
